export const URL = "http://localhost:8080";
export const URL_USER = "http://bw.ausgrads.academy:10000/grizzlystore-user_service"

export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_REJECTED = "FETCH_CATEGORIES_REJECTED";
export const FETCH_CATEGORY_ITEMS_FULFILLED = "FETCH_CATEGORY_ITEMS_FULFILLED";
export const FETCH_CATEGORY_ITEMS = "FETCH_CATEGORY_ITEMS";
export const FETCH_CATEGORY_ITEMS_REJECTED = "FETCH_CATEGORY_ITEMS_REJECTED";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ITEMS_FULFILLED = "FETCH_ITEMS_FULFILLED";
export const FETCH_ITEMS_REJECTED = "FETCH_ITEMS_REJECTED";

export const FETCH_ITEMS_PAGE = "FETCH_ITEMS_PAGE";
export const FETCH_ITEMS_PAGE_FULFILLED = "FETCH_ITEMS_PAGE_FULFILLED";
export const FETCH_ITEMS_PAGE_REJECTED = "FETCH_ITEMS_PAGE_REJECTED";

export const FETCH_SINGLE_ITEM = "FETCH_SINGLE_ITEM";
export const FETCH_SINGLE_ITEM_FULFILLED = "FETCH_SINGLE_ITEM_FULFILLED";
export const FETCH_SINGLE_ITEM_REJECTED = "FETCH_SINGLE_ITEM_REJECTED";

export const FETCH_ITEM_CATEGORY = "FETCH_ITEM_CATEGORY";
export const FETCH_ITEM_CATEGORY_FULFILLED = "FETCH_ITEM_CATEGORY_FULFILLED";
export const FETCH_ITEM_CATEGORY_REJECTED = "FETCH_ITEM_CATEGORY_REJECTED";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESSFUL = "ADD_CATEGORY_SUCCESSFUL";
export const ADD_CATEGORY_REJECTED = "ADD_CATEGORY_REJECTED";

export const SERVER_NOT_FOUND = "SERVER_NOT_FOUND";

export const GOOGLE_USER = "GOOGLE_USER";
export const NORMAL_USER = "NORMAL_USER";

